server:
  port: 8888
  servlet:
    context-path: /
    session:
      cookie:
        max-age: 180



spring:
  #jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/db_webshop?useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  #关模板引擎缓存
  thymeleaf:
    cache: false
#  设置multipartfile的上传文件大小和request请求的大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#  设置虚拟路径：：匹配所有项目路径下的虚拟路径，增加文件的虚拟映射
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file.uploadFolder}

#别名
mybatis:
  type-aliases-package: com.github.webshop.pojo
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml

